---
title: "DDS_Unit2_Homework"
author: "Steven Garrity"
date: "9/1/2019"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(tidyverse)
```

```{r "ls", echo=FALSE}
system("ls")
```

## Load Data:
```{r playerbb, results='hide'}
playerbb = read.csv("/Users/stevengarrity/SMU_MSDS/DS6306_DoingDataScience/DDS_Git/Unit 2/PlayersBBall.csv", header = TRUE)
summary(playerbb)
```

## Question 1
Use the PlayerBBall.csv dataset to visually represent (summarize) the number of players in each position.

```{r, echo=FALSE}
playerbb %>% ggplot(aes(x=position, fill=position)) + geom_bar() + ggtitle("Number of Players in Each Position")
```

## Question 2
Use the dataset to visually investigate the distribution of the weight of centers (C) is greater than the distribution of the weight of forwards (F).

```{r}
# test <- playerbb %>% pull(weight)
player_weights <- playerbb[(playerbb$position == "C" | playerbb$position == "F"),]

# the next two plots are identical, however, I can't get a legend to show
ggplot(playerbb, aes(x=weight)) +
  geom_histogram(data=subset(playerbb, position == "F"), color = "black", fill = "blue", alpha = 0.7) +
  geom_histogram(data=subset(playerbb, position == "C"), color = "black", fill = "red", alpha = 0.7)

ggplot(player_weights, aes(x=weight)) +
  geom_histogram(data=subset(player_weights, position == "F"), color = "black", fill = "blue", alpha = 0.7) +
  geom_histogram(data=subset(player_weights, position == "C"), color = "black", fill = "red", alpha = 0.7)

# try something different
weight_C <- subset(playerbb, position == "C", select=c(weight,position))
weight_F <- subset(playerbb, position == "F", select=c(weight,position))
weights = rbind(weight_C$weight,weight_F$weight)

player_weights = data.frame(weight = rbind(weight_C$weight, weight_F$weight),
                            position = rbind(weight_C$position, weight_F$position))

player_weights %>% ggplot(aes(x=weight), fill = position)
  

```

# Question 3

```{r}
## for height-related questions:
temp_var <- str_split_fixed(playerbb$height,n = 2,pattern = "-")
total_height_inches = as.numeric(temp_var[,1])+(as.numeric(temp_var[,2])/12)
```


