---
title: "DDS HW4"
author: "Steven Garrity"
date: "9/15/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(XML)
library(tidyverse)
library(ggplot2)
library(GGally)
```

# Part 1
```{r}
sushi <- read_html("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Frestaurants.xml")
sushi_nameR <- html_nodes(sushi,"name")
sushi_name <- stri_sub(sushi_nameR,7,-8)
sushi_zipcodeR <- html_nodes(sushi, "zipcode")
sushi_zipcode <- stri_sub(sushi_zipcodeR,10,-11)
sushi_councilR <- html_nodes(sushi, "councildistrict")
sushi_council <- stri_sub(sushi_councilR,18,-19)

df_sushi <- data.frame(name = sushi_name, zipcode = sushi_zipcode, council=sushi_council)
str(df_sushi)

grep("sushi", ignore.case = TRUE, df_sushi$name)
length(grep("sushi", ignore.case = TRUE, df_sushi$name))
# grepl("sushi", ignore.case = TRUE, df_sushi$name)
# sum(grepl("sushi", ignore.case = TRUE, df_sushi$name))


#### How many sushi restaurants downtown:
df_sushi_11 <- df_sushi %>% filter(council == 11)
length(grep("sushi", ignore.case = TRUE, df_sushi_11$name))
df_sushi_11[grep("sushi", ignore.case = TRUE, df_sushi_11$name),]

sushi_by_council <- df_sushi[grep("sushi", ignore.case = TRUE, df_sushi$name),]

#### How many sushi restaurants in each council:
sushi_by_council_summarize <- sushi_by_council %>% group_by(council) %>% summarize(count = n())

sushi_by_council_summarize$council =
  factor(sushi_by_council_summarize$council,
         level = sushi_by_council_summarize$council[order(as.numeric(as.character(sushi_by_council_summarize$council)))])

sushi_by_council_summarize %>% ggplot(aes(x = council, y = count)) + geom_col() +
  labs(title="Number of Sushi Restaurants by Council District in Baltimore, MD", y="Number of Restaurants", x ="Council")

```

# Part 2
```{r}
library(openair)
#load metadata for all sites:
aurn_detailed <- importMeta(source = "aurn", all = TRUE)

library(leaflet)

m <- leaflet() %>%
  addProviderTiles(providers$NASAGIBS.ViirsEarthAtNight2012) %>% # default OpenStreetMap map tiles
  # addMarkers(lng=aurn_detailed$longitude, lat=aurn_detailed$latitude, popup = aurn_detailed$code)
addCircleMarkers(lng=aurn_detailed$longitude[aurn_detailed$code == "CHBO" | aurn_detailed$code == "MY1"], lat=aurn_detailed$latitude[aurn_detailed$code == "CHBO" | aurn_detailed$code == "MY1"],
    radius = 10,
    color = "red",
    stroke = FALSE, fillOpacity = 0.2,
    popup = aurn_detailed$code[aurn_detailed$code == "CHBO" | aurn_detailed$code == "MY1"])

m

m2 <- leaflet() %>%
  addProviderTiles(providers$Wikimedia) %>%
  addCircleMarkers(lng=aurn_detailed$longitude, lat=aurn_detailed$latitude, radius = 6, color = "navy", stroke = FALSE, fillOpacity = 0.2, popup = aurn_detailed$code) %>%
  addCircleMarkers(lng=aurn_detailed$longitude[aurn_detailed$code == "CHBO" | aurn_detailed$code == "MY1"], lat=aurn_detailed$latitude[aurn_detailed$code == "CHBO" |aurn_detailed$code == "MY1"],    radius = 6, color = "red", stroke = FALSE, fillOpacity = 0.5, popup = aurn_detailed$code[aurn_detailed$code == "CHBO" | aurn_detailed$code == "MY1"])

m2
  

# list all parameters
str(aurn_detailed$parameter)

# list all urban sites
urban_background_sites <- filter(aurn_detailed, site.type == "Urban Background")
nrow(urban_background_sites)

# list all rural sites
rural_background_sites <- filter(aurn_detailed, site.type == "Rural Background")
nrow(rural_background_sites)


chbo <- importAURN(site= "CHBO", year = 2018)
str(chbo)
my1 <- importAURN(site = "MY1", year = 2018)
str(my1)

# require(plyr)
alldata = rbind.fill(my1,chbo)
head(alldata)
tail(alldata)

# alldata$rating <- as.numeric(q2_fifa$Overall)
alldata$windCardinal = cut(alldata$wd, breaks = c(0,90,180,270,360), labels = c("NE","SE","SW","NW"))
```

# EDA - Step 2
```{r}
alldata %>% select(o3, so2, pm2.5, windCardinal) %>% ggpairs(aes(color=alldata$code, alpha=0.2)) + ggtitle("Urban vs Rural Air Pollutants")
```

# EDA - Windroses
```{r}
windRose(my1, type = "season", pollutant = "nox", cols="heat", width=0.5, offset=15)
windRose(chbo, type = "season", pollutant = "nox", cols="heat", width=0.5, offset=15)
```

# EDA - calendar plots
```{r}
calendarPlot(chbo, pollutant = "o3", annotate = "value", lim =90,
cols = "Purples", col.lim = c("black", "orange"),
layout = c(4, 3))
```


